# Generated by Django 5.0.7 on 2024-08-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
                ('category_description', models.CharField(max_length=200)),
                ('category_image', models.ImageField(upload_to='images/category/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=80)),
                ('movie_description', models.CharField(max_length=200)),
                ('movie_image', models.ImageField(upload_to='images/Movies/')),
                ('movie_price', models.PositiveIntegerField()),
                ('movie_date', models.DateTimeField()),
                ('movie_time', models.TimeField()),
                ('shows', models.CharField(choices=[('First_Show', 'first show'), ('Second_Show', 'Second show'), ('Evening_Show', 'Evening show'), ('Night_Show', 'Night show')], default='Night_Show', max_length=30)),
                ('movie_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='mainapp.movie')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('show', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.seat')),
            ],
        ),
    ]
