# Generated by Django 5.0.7 on 2024-08-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='seat',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='SeatFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.movie')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('show', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='SeatOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.movie')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('show', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='SeatThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.movie')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('show', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='SeatTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.movie')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('show', 'seat_number')},
            },
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
